### ISSUE TITLE
Task list (pre mvp demo)

### ISSUE THREAD

**Issue by jaxernst** [jaxernst/puzzle-bets#1]
- [x] * Remove hardcoded eth prices
- [x] * Fix modal screen overlay can get 'moved' (uncovers the underlaying content)
- [x] * The game selector will say 'ready to solve' even after solution has been submitted
- [x] * When switching between games, the game state has to load every time (slow and there's no loading spinner)
- [x] * Confetti hits every time you switch between solved games
- [x] * Add back button to escape from a gameid
- [x] * Confetti falls flat at the bottom of the screen
- [x] * Game should only be marked as complete once both players withdraw
- [x] * Don't let players guess more after deadline
- [x] * Auto archive expired invites
- [x] * Add 'archive' button to completed games
- [x] * Show players final game state or allow players to 'share results'
- [x] * Make invite link previews (Add page header content to indicate those links are invites)
- [x] * Fix shaking tiles for incorrect answers
- [x] * Make it clear that demo games are Demo games
- [x] * Replace how to with color key
- [x] * Figure out how to allow games to reset after both players submit
           * Might also be nice to have a 'vote to replay' option too
- [x] Disable submit button when out of guesses
- [x] ^ Also hide the countdown timer and say something like 'You're out of guesses' the results will be revealed in ...seconds'
- [x] Show correct answer when time runs out
- [x] Add loading spinners while puzzle is loading
- [x] Disable submit while invite is pending
- [x] Demo game is slow to load and has caused 500 errors
- [ ] Change 'view results + claim' into '$xx won or '$xx lost'
- [x] PWAify and add notifications
- [x] Prevent double guesses entries
- [x] Auto open the game selector tab that the current route's game falls under
- [x] Figure out why Warpcast link previews don't show nicely
- [x] Show loader when join game modal is waiting for mud to sync
- [ ] Allow games to be archived after you have withdrawn
- [x] Show loading dots when puzzle is being reset
- [x] ios safari new game value input is janky
- [x] Change archive button
- [x] Don't display vote to rematch if someone has claimed
- [x] Fix and test link previews
- [x] Make join button work
- [x] Add rematch request notifications
