### ISSUE TITLE
Task List (pre mainnet)

### ISSUE THREAD

**Issue by jaxernst** [jaxernst/puzzle-bets#2]
- [ ] Add game fee system
- [ ] Add embedded wallet auth
- [ ] Add backend signature verification
- [ ] Add wallet/profile 'nicknames' 
- [ ] Add backend game state checks (for reset, checking opponents, etc)
- [ ] Add 'lobby' matchmaking
- [ ]
